### ISSUE TITLE
Rhythmbox audio not working after opening firetools

### ISSUE THREAD

**Issue by nixoye** [netblue30/firetools#10]
Every time i launch firetools Rythmbox's audio can't be heard. The song still plays and audio from my web browser still plays fine so its only affecting the audio from Rythmbox.

**Comment by netblue30** [comment]
There is a PulseAudio bug that is creating sound problems for most users. You would need to configure pulseaudio as described here:

https://firejail.wordpress.com/support/known-problems/#pulseaudio

Once configured, reboot your computer for the configuration to take place.

**Comment by rusty-snake** [comment]
@netblue30 I think that can be closed.

**Comment by Fred-Barclay** [comment]
Closing for now @NIXOYE please feel free to re-open if you have any further questions. :smile:
