### ISSUE TITLE
Icons in firetools

### ISSUE THREAD

**Issue by viking777** [netblue30/firetools#13]
How to get icons to show up in firetools when they are not picked up automatically?
Example kmymoney - icon is in /usr/share/icons but is not shown by firetools.

**Comment by netblue30** [comment]
Until I fix it, copy the icon file by hand in ~/.config/firetools directory.

**Comment by viking777** [comment]
Don't know if this will help you at all, but I found out by looking into the .desktop files in ~/.config/firetools, the link to the icon started with an uppercase letter 'K' whereas the actual icon in usr/share/icons has a lowercase 'k'. When I corrected that and restarted firetools kmymoney icon was there. 
Another missing icon problem was solved by placing the full path to the icon in the 'icon=' one of the desktop file.

**Comment by netblue30** [comment]
Yes, somehow I have to make the icon search case insensitive. I've seen this issue with some other programs, where the program starts lowercase and the icon starts uppercase. Anyway, I'll put the fix in for the next release, thank you for reporting it.

**Comment by netblue30** [comment]
Fixed in 0.9.50.
