### ISSUE TITLE
Make “Firejail Tools and Stats” independent of the red launcher window and the latter one optional

### ISSUE THREAD

**Issue by stryx** [netblue30/firetools#14]
I really enjoy the monitoring features of the “Firejail Tools and Stats” window. But I don't need the red window for launching jailed applications at all. It's just not needed, in the way, and I don't like its look very much.

So far I couldn't find a way to get rid of the launcher window while keeping the “Tools and Stats”. If there is one, please tell me about. If not it would be great to have it at some point!

Thank you!

**Comment by netblue30** [comment]
Will do!

**Comment by netblue30** [comment]
All done in the latest version in git.
