### ISSUE TITLE
Firetools dependencies?

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#16]

**Comment by netblue30** [comment]
I don't remember exactly, start with qt5-default and if it still doesn't work add qt5-qmake and qtbase5-dev-tools.

**Comment by rekixex** [comment]
@netblue30 Thanks, now it does work.

I started with `sudo apt-get install qt5-default` as you said, about 70 packages were installed consequently. After that I checked for system updates via Update Manager but it reported broken dependencies and suggested to run `sudo apt-get install -f` to fix them. After `sudo apt-get install -f` I checked for system updates again and it found about 20 updates related to qt5. Probably should have restarted after installing qt5-default...

You can close this (and maybe add to documentation suggestion to install qt5-default before compiling Firetools from the source code?).

**Comment by rekixex** [comment]
@netblue30 Thanks, now it does work.

I started with `sudo apt-get install qt5-default` as you said, about 70 packages were installed consequently. After that I checked for system updates via Update Manager but it reported broken dependencies and suggested to run `sudo apt-get install -f` to fix them. After `sudo apt-get install -f` I checked for system updates again and it found about 20 updates related to qt5. Probably should have restarted after installing qt5-default...

You can close this (and maybe add to documentation suggestion to install `qt5-default` before compiling Firetools from the source code?).

**Comment by rekixex** [comment]
@netblue30 Thanks, now it does work.

I started with `sudo apt-get install qt5-default` as you said, about 70 packages were installed consequently. After that I checked for system updates via Update Manager but it reported broken dependencies and suggested to run `sudo apt-get install -f` to fix them. After `sudo apt-get install -f` I checked for system updates again and it found about 20 updates related to qt5. Probably should have restarted after installing `qt5-default`...

You can close this (and maybe add to documentation suggestion to install `qt5-default` before compiling Firetools from the source code?).

**Comment by netblue30** [comment]
I'll write something down in the README file and close the issue after that, thanks for bringing it up.

**Comment by rekixex** [comment]
@netblue30 No problem. Thank you for this project. Excellent GUI addition to Firejail. :)
