### ISSUE TITLE
Should not delete entire rpmbuild tree

### ISSUE THREAD

**Issue by ssabchew** [netblue30/firetools#2]
Please do not delete the entire rpmbuild tree, but only related files instead.
May be you can use something like:

find  $HOME/rpmbuild/  -iname firetools | xargs rm -rf $1

Or use some $NAME-$VERSION variables

**Comment by netblue30** [comment]
Sure, I'll look into it.

**Comment by wtogami** [comment]
This was fixed by PR #11 you can close this issue.

**Comment by netblue30** [comment]
Closed, thanks.
