### ISSUE TITLE
(minor) firetools current process window sizing

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [netblue30/firetools#20]
Hi !

I'm on Ubuntu 16.04 and I noticed a minor annoyance in firetools. When I display the current process window I get this :
![1](https://cloud.githubusercontent.com/assets/26625900/25295086/667e1262-26e2-11e7-9ecc-3027fc742806.jpg)

But what I would really like after resizing is this :
![2](https://cloud.githubusercontent.com/assets/26625900/25295090/6bbb10fe-26e2-11e7-9e8d-6780ab633a70.jpg)

It's annoying ot have to resize it every time I open it just to see precisely which command is running.
Isn't there a way to remember the former size ? Or just to have it display large enough to print in one line the process ?

Thank you and great work so far :)

**Comment by netblue30** [comment]
Somehow I'll have to try to match the font with the size of the window, instead of setting a default window size. Thanks for the bug.

**Comment by netblue30** [comment]
I added support to store the window size in a file in ~/.config/firetools directory when the application is closed. When you restart the application, it will come up with the last size stored.
