### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by reinerh** [netblue30/firetools#27]
In README you document the license of the LibreOffice Writer icon like this:
> Libreoffice-writer (libreoffice-writer.png) taken from Gnome project, license LGPL v3 or CC BY-SA 3.0.

As far as I can see, the icons are coming from LibreOffice itself?
(Here is the original svg icon: https://sources.debian.net/src/libreoffice/1:5.4.0-1/sysui/desktop/icons/hicolor/scalable/apps/ )

**Comment by netblue30** [comment]
I am kind of lost in this licensing thing.

I took it from /usr/share/icons/gnome/48x48/apps/libreoffice-writer.png on Ubuntu Gnome 17.04.

There is also one in /usr/share/icons/hicolor/48x48/libreoffice-writer.png. I guess all of them are sourced form the one you mentioned (svg in LibreOffice). Should we change the credits it to LibreOffice?

**Comment by reinerh** [comment]
At least on Debian this icon is also coming from the libreoffice package:
> $ dpkg -S /usr/share/icons/gnome/48x48/apps/libreoffice-writer.png
> libreoffice-common: /usr/share/icons/gnome/48x48/apps/libreoffice-writer.png

If I see it correctly (https://wiki.documentfoundation.org/Gallery_Icons), the license is CC-BY-SA-3.0 or LGPL-3+ or MPL-1.1. (I will document this also in Debian's copyright file)
