### ISSUE TITLE
Can't install in Whonix (Couldn't find any package by rege)

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firetools#31]
Tried with and without .deb extension. Following error:

```
root@host:/home/user/Downloads#` dir
firetools_0.9.52_1_i386.deb
root@host:/home/user/Downloads# apt-get install firetools_0.9.52_1_i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package firetools_0.9.52_1_i386
E:  'firetools_0.9.52_1_i386'
root@host:/home/user/Downloads# 

```

**Comment by Fred-Barclay** [comment]
Hi @Futureknows 
Usually `apt-get` looks for a package in the repositories. To install from a local file, try using `dpkg -i` or `gdebi` as described [here](https://superuser.com/questions/196864/how-to-install-local-deb-packages-with-apt-get#196867).
