### ISSUE TITLE
Displaying namespaces in firestats

### ISSUE THREAD

**Issue by Futureknows** [netblue30/firetools#32]
When launching a firejail with the net= paremeter the namespace creation shows the relevant details:

`Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP    
eth0-12628       fa:10:92:f6:ce:87  192.168.1.249    255.255.255.0    UP    
eth1-12628       66:71:f5:09:63:47  192.168.1.196    255.255.255.0    UP    
Default gateway 192.168.1.1
`
However when launching from an icon you never get to see these details. It would be very useful if the namespace details were displayed from within firestats under the PID details page.

**Comment by netblue30** [comment]
Implemented in 0.9.58. Thanks for your suggestion.
