### ISSUE TITLE
Add Use FireJail by Default Options

### ISSUE THREAD

**Issue by asddsaz** [netblue30/firetools#34]
**Short Explanation**: A configuration option to allow for an application to automatically use a FireJail profile if he/she utilized a built in DE launcher like Gnome or KDE.

**Long Explanation**: It would be great to have it so that when I launch an jailed application via your normal application launcher. There are some shortcut editors like [AppEditor](https://github.com/donadigo/appeditor) for Ubuntu, that will let you execute terminal commands when you click a shortcut.

It would make things much easier if FireTools could have this as a feature adding to the overall ecosystem.

**Comment by rusty-snake** [comment]
@asddsaz did you checkout [this](https://github.com/netblue30/firejail#desktop-integration)?

**Comment by netblue30** [comment]
Yes, it is already implemented as part of desktop integration feature in firejail. You would need to run "sudo firecfg" in a terminal.
