### ISSUE TITLE
add tools to systray menu

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#37]
hello, it's pretty painful to have to open the  widget, run Tools, close the widget, each time that you want to open Tools, it is possible to add it to the systray context menu ?

thanks

**Comment by netblue30** [comment]
Will do!

**Comment by startx2017** [comment]
fixed in git:

 https://github.com/netblue30/firetools/commit/4e05453ddb96db78f1b326b86baa0b6111729218
