### ISSUE TITLE
Configuration wizard compatibility with dark themes

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#38]
When using a dark theme some issues are very noticeable:

* All steps: white "Firejail reduces the risk ..." text is not legible on its light background
* All steps: black checkboxes' and radio buttons' marks are not legible on dark background
* Step 1: black text in application list is not legible on dark background
* Step 3: white Network pane, both background and text, compared to black colors in other panes
* Step 3 (continued), Kernel pane: "Enable seccomp-bpf" has white text compared to black texts of other options
* In a maximized window, the background image looks terrible.
* Besides, people use dark themes for a reason and a white background image defeats that

![01](https://user-images.githubusercontent.com/19147756/52102353-d745a800-2601-11e9-8701-49df757f62a4.png)
![02](https://user-images.githubusercontent.com/19147756/52102360-df054c80-2601-11e9-8b7d-75cd4a2ab065.png)
![03](https://user-images.githubusercontent.com/19147756/52102365-e4629700-2601-11e9-89d3-8eb323f6c7a4.png)

**Comment by netblue30** [comment]
> text is not legible on its light background...

Definitely a bug, thanks!

**Comment by startx2017** [comment]
Fix in git: https://github.com/netblue30/firetools/commit/2a8f6a238ca4a93fb67abc24106f903fd9a4827f

**Comment by jakob1379** [comment]
I am sorry for bumping this one, but it does not seem to be fixed for me. I have tried with a variety of themes through lxappearance to set the themes which work for my other applications.

![2020-04-18-051357_960x600_scrot](https://user-images.githubusercontent.com/17257805/79626877-180cdc80-8134-11ea-85b1-f976b0a8787c.png)

System info:
`System:    Host: fuzie-laptop Kernel: 5.4.35-1-MANJARO x86_64 bits: 64 Desktop: i3 4.18.1 Distro: Manjaro Linux`

**Comment by JJRcop** [comment]
I have the same behavior as @jakob1379. 
```sh
$ firejail-ui --version
Firejail-ui version 0.9.62
```
Running Debian Testing (bullseye) with KDE, let me know if there is any other info you need to help debug this

![Screenshot_20200429_201820](https://user-images.githubusercontent.com/5211576/80659304-929ffb00-8a56-11ea-93e3-c58c74bfb17a.png)

**Comment by rusty-snake** [comment]
[Ping](https://github.com/netblue30/firejail/issues/3541) [Pong](https://github.com/netblue30/firejail/issues/3544)

**Comment by JJRcop** [comment]
Can this issue be reopened? This still appears in the most recent release

**Comment by drujd** [comment]
Same problem here. Plasma 5.19.4, Breeze Dark theme (for everything including GTK apps)...

**Comment by Foosec** [comment]
Same thing, Manjaro i3, dark themed
