### ISSUE TITLE
Project ERROR: Library 'libatomic' not defined

### ISSUE THREAD

**Issue by Ciphergyst** [netblue30/firetools#42]
Failing to configure/install with both git clone and tar versions
Project ERROR: Library 'libatomic' is not defined.
./configure: line 3971: cd: src/firejail-ui: No such file or directory
./configure: line 3972: cd: src/fstats: No such file or directory
./configure: line 3973: cd: src/fmgr: No such file or directory
cp: cannot stat 'confdefs.h': No such file or directory
sed: can't read confdefs.h: No such file or directory
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

Any workarounds? Dependencies have been satisfied

**Comment by startx2017** [comment]
What gcc version do you have (gcc -v) and what distribution are you on?

**Comment by Ciphergyst** [comment]
I've since switched Distros, I was on KDE Neon. I just re-ran the build on Ubuntu 19.04 and it was successful

**Comment by startx2017** [comment]
Thanks, keep an eye on it. If you get it again I'll reopen the bug. It is probably something to do with the way gcc is set up on their platform.
