### ISSUE TITLE
KDE unreadable font in firejail-ui

### ISSUE THREAD

**Issue by dalechyn** [netblue30/firetools#43]
Font's are not working correct on black-themed KDE:
![image](https://user-images.githubusercontent.com/35642018/60389713-7eeed580-9acf-11e9-9a46-93915d14f41b.png)

**Comment by rusty-snake** [comment]
Duplicate of #38

**Comment by startx2017** [comment]
Fix in git:  https://github.com/netblue30/firetools/commit/2a8f6a238ca4a93fb67abc24106f903fd9a4827f
