### ISSUE TITLE
D'nt start firetools 0.9.58

### ISSUE THREAD

**Issue by SergeyDjam** [netblue30/firetools#44]
ROSA Fresh R11

firetools-0.9.52 start
firetools-0.9.58 not start

![https://i.imgur.com/RjP9uMJ.png](https://i.imgur.com/RjP9uMJ.png)

`%build 

autoreconf -if
./configure --prefix=/usr --with-qmake=%{_bindir}/qmake-qt5
%make
`

what fix it?

**Comment by netblue30** [comment]
We have a 0.9.62 version out. Can you give it a try? Thanks.

**Comment by SergeyDjam** [comment]
I testing 0.9.62, this release fix problem

**Comment by netblue30** [comment]
OK, thanks! I'll close it for now.
