### ISSUE TITLE
Fails to sandbox an app

### ISSUE THREAD

**Issue by DurtyDev** [netblue30/firetools#47]
Firejail cannot keep an app named Clipgrab in the sandbox. No matter what it will not sandbox.

**Comment by rusty-snake** [comment]
How do you start it? How do you detect that it is not running in firejail?

What shows `firejail --tree | grep clipgrab` after starting clipgrab?

**Comment by DurtyDev** [comment]
On Wed, Jan 22, 2020, 8:36 AM rusty-snake <notifications@github.com> wrote:

> How do you start it? How do you detect that it is not running in firejail?
>
> —
>




I start try to start it like I would any other app. I choose the app from a
list as it doesn't have a predefined rule like Gimp and Firefox do. Only
when I choose the app image firetools promptly informs me that the image
isn't executable. ( I luauched Clipgrab 3 times hoping the system would
catch on. )  I even resorted to command line sudo firejail clipgrab , sudo
this sudo that. Nothing worked.  I wanted that app in jail as when I
attempted to close Clipgrab it went right to my system tray  were it stayed
while I opened my  tasker to see 86 threads and 302 mb memory and fkill it.
I played with the apps all night. Clipgrab works but weather you give it
permission by checking the box or not it goes right to sys tray.  I emailed
the dev on that also as a former Windows user apps that force themselves in
to the tray usually have bad intentions.
If you would like to video conference to see I would be more than happy.

>

**Comment by rusty-snake** [comment]
I just tried with firejail git-master, Fedora 31, ClipGrab 3.8.9 and the following firejail profile (firejail 0.9.62+).

<details> <summary> clipgrab.profile </summary>

```
# Firejail profile for clipgrab
# Description: DESCRIPTION
# This file is overwritten after every install/update
# Persistent local customizations
include clipgrab.local
# Persistent global definitions
#include globals.local

noblacklist ${HOME}/.config/Philipp Schmieder
noblacklist ${HOME}/.pki
noblacklist ${VIDEOS}

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-xdg.inc

include whitelist-usr-share-common.inc
include whitelist-var-common.inc

apparmor
caps.drop all
machine-id
netfilter
nodbus
nodvd
nogroups
nonewprivs
noroot
nosound
notv
nou2f
novideo
protocol unix,inet,inet6,netlink
seccomp !chroot
shell none

disable-mnt
private-cache
private-dev
private-tmp
```

</details>

 - `nodbus` will break the tray function.
 - `seccomp` blocks `chroot` (syscall, not program) which is needed by QtWebengie. You will have something like `… SECCOMP … comm="QtWebEngineProc" exe="/usr/lib64/qt5/libexec/QtWebEngineProcess" sig=31 arch=c000003e syscall=161 …` in your journal.

**Solutions:** Allow `chroot` by not using `seccomp` or adding an exception (firejail 0.9.62)/using `seccomp.drop` (firejail <0.9.62).

**Comment by DurtyDev** [comment]
Thanks I'm fixing to give that a try.
That's why I'm not a dev. I can't write a lick of code. I can build a sweet
website. Thanks 😊 I'm fixing to see if it works. Hat's off to you. I still
haven't heard from the dev of the offending app.  I will let you know the
outcome .

**Comment by rusty-snake** [comment]
If this profile works for you I can bring it upstream.

**Comment by DurtyDev** [comment]
It works on my end. Manjaro KDE desktop. Thank you. Sorry it took so long.
I'm a night owl 🦉.

The dev from Clipgrab messaged me saying that my window manager was the
problem.  👀🧐 Nahhhh. Lol

**Comment by DurtyDev** [comment]
The response I got from Clipgrab. Wow.


---------- Forwarded message ---------
From: Joe Durt <cheif.bigmeat@gmail.com>
Date: Wed, Jan 22, 2020, 5:14 PM
Subject: Fwd: Clipgrab Permissions
To: <captaincrazy240@gmail.com>



---------- Forwarded message ---------
From: Joe Durt <cheif.bigmeat@gmail.com>
Date: Wed, Jan 22, 2020, 5:13 PM
Subject: Re: Clipgrab Permissions
To: Philipp from ClipGrab <support@clipgrab.org>


Bro , it sits in the sys tray with 86 background threads and you haveto
fkill it...It refused firejail sandbox. I have no problem removing or
closing any other app in the system tray. Sir wish all due respect , while
the program does download and convert like it says , it's not supposed to
refuse being closed out, or sandboxing

**Comment by rusty-snake** [comment]
Issue can be closed.
