### ISSUE TITLE
patch included in firecfg.config, breaks it

### ISSUE THREAD

**Issue by zupatisc** [netblue30/firetools#55]
It seems that patch was added to the firecfg.config and until I manuall removed the entry patch would fail, reporting that it cannot access /usr/lib/libdl.so.2

Edit: Guess this belongs into the other repo

**Comment by rusty-snake** [comment]
> Edit: Guess this belongs into the other repo

https://github.com/netblue30/firejail/issues

> reporting that it cannot access /usr/lib/libdl.so.2

Does it work if you add `libdl.so.*` to the `private-lib` line in patch.profile?

**Comment by zupatisc** [comment]
> > Edit: Guess this belongs into the other repo
> 
> https://github.com/netblue30/firejail/issues

Sorry about that.
> > reporting that it cannot access /usr/lib/libdl.so.2
> 
> Does it work if you add `libdl.so.*` to the `private-lib` line in patch.profile?

Yes if I do that patch works as expected again.

**Comment by rusty-snake** [comment]
> > > reporting that it cannot access /usr/lib/libdl.so.2
> > 
> > 
> > Does it work if you add `libdl.so.*` to the `private-lib` line in patch.profile?
> 
> Yes if I do that patch works as expected again.

Your welcome to open a PR.
