### ISSUE TITLE
How do I install Tor Browser and ProntonVPN in Firetools ?

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#59]
Hello everybody
I have 2 questions 

1.   
I have installed Tor Browser from Software Manager in Linux Mint Xfce .  
It works but how can I install Tor browser in Firetools?   
https://firejailtools.wordpress.com/screenshots/    
With Edit / Command / firejail tor browser does not work .     

2.   
And how can I install the free version of ProtonVPN in Firetools ?  
I installed ProtonVPN DEB package on Linux Mint Xfce like this .  
https://protonvpn.com/support/official-linux-vpn-mint/    
It works but how can I install ProtonVPN in Firetools? 
Also this I can not install with Edit / Command /  firejail protonvpn .   

Can someone explain me how to install these 2 programs in Firetools ?  

(I am a beginner )

**Comment by rusty-snake** [comment]
_Looks like I'm really the only person answering questions here ..._

1. The tor-browser can not be installed via apt (out of the way it works). Anyway tor-browser-launcher was written for this reason, so that probably the command you need (open a terminal and type `tor<TAB>` to see which programs starting with `tor` are installed).
2. ProtonVPN has no firejail profile therefore it can be a bit more complicated (and IDK how it works / what features it has). At first you should make sure that `firejail protonvpn` (in a terminal) works as expected.

**Comment by ghost** [comment]
(sorry , maybe i explained it wrong because i am using a translate because my English is not that good .)         

I installed Tor Browser from Program Management like this:      
https://ibb.co/VL2D6GC    
It works good but how can I install Tor browser with a start button in Firetools  ?    

If I can't install it that way , is it even possible to install Tor browser with a start button in Firetools 
 with the downloaded Tor Browser version ?
https://www.torproject.org/download/    

P.s. I have a computer

**Comment by rusty-snake** [comment]
Yeah, Tor Browser Launcher as I said. Does `firejail torbrowser-launcher` work?

**Comment by ghost** [comment]
Tor Browser Launcher is from the Program Management right? .    
When I type firejail torbrowser-launcher  into terminal I get this . 
https://ibb.co/X8QYWCZ       
(I don't understand much about it)

**Comment by rusty-snake** [comment]
Did you installed the flatpak? In that case you can not use firejail (and don't need it).

**Comment by ghost** [comment]
yes it is a flatpak .    
     

But what about the downloaded Tor browser version .
Can I install the downloaded Tor browser version in Firetools ? (with a start button)     

I found this video but it does not make a start button in Firetools .

https://www.youtube.com/watch?v=293D-Cu3KuM   

     

And which of the 2 (Tor Browser Launcher from Program Management or the downloaded Tor Browser version from TOR own site )   is safer ?

**Comment by rusty-snake** [comment]
> And which of the 2 (Tor Browser Launcher from Program Management or the downloaded Tor Browser version from TOR own site ) is safer ?

Safer (or more secure) for what? The software itself is the same. Tor Browser Launcher is just a program that automate the manual setup of the tor-browser.

> ## Tor Browser Launcher
>
> […]
>
> Tor Browser Launcher is intended to make Tor Browser easier to install and use for GNU/Linux users.
> You install `torbrowser-launcher` from your distribution's package manager and it handles everything else:
>
> * Downloads and installs the most recent version of Tor Browser in your language and for your computer's architecture, or launches Tor Browser if it's already installed (Tor Browser will automatically update itself)
> * Verifies Tor Browser's [signature](https://www.torproject.org/docs/verifying-signatures.html.en) for you, to ensure the version you downloaded was cryptographically signed by Tor developers and was not tampered with
> * Adds "Tor Browser" and "Tor Browser Launcher Settings" application launcher to your desktop environment's menu

<sub>src: https://github.com/micahflee/torbrowser-launcher/blob/develop/README.md</sub>

**Comment by ghost** [comment]
okay I didn't know that the software itself are the same.   I thought the downloaded version was a Portable version .   
So if i understood correctly then it is enough to just install Tor Browser launcher from the distribution's package manager and it is not necessary to install Tor in Firetools because a flatpak itself already runs in a sandbox .    

Thank you very much for your help and explanation .
