### ISSUE TITLE
Build failure on some architectures

### ISSUE THREAD

**Issue by reinerh** [netblue30/firetools#6]
Hi,

firetools can't be built on architectures other than amd64 in Debian [1].
The reason is a check for a hardcoded path in configure.ac.
I would suggest to drop the whole blocks checking manually for Qt and replace it with a pkg-config check:
`PKG_CHECK_MODULES(QT5, [Qt5Widgets], [], AC_MSG_ERROR([*** Qt5 not installed]))`
(I also think you no longer need to support Qt4, so this line should be sufficient.)

I think the checks for Qt5svg are also not necessary, since it is not required during build time (it doesn't include or link against it).
And you could also drop the check for firejail and xterm in configure.ac, since they are also no build requirements.

1: https://buildd.debian.org/status/logs.php?pkg=firetools&ver=0.9.30-1&suite=sid

**Comment by netblue30** [comment]
Sure, I'll drop xterm and qt5svg dependency, I'll make them warnings. Also, I'll drop the support for Qt4 - both Ubuntu 14.04 and wheezy have qt5 support. Thanks!

**Comment by netblue30** [comment]
I am all set in this moment, give it a try and I'll reopen it if necessary. Thanks!
