### ISSUE TITLE
Patch for Alpine Linux support in configure

### ISSUE THREAD

**Issue by itoffshore** [netblue30/firetools#7]
I'm adding [firejail](http://patchwork.alpinelinux.org/patch/1997/) & [firetools](http://patchwork.alpinelinux.org/patch/1998/) to [Alpine Linux](http://alpinelinux.org/).

The following patch works for `qt4` & `qt5`:

```
--- firetools-0.9.30/configure
+++ firetools-0.9.30/configure.new
@@ -3811,18 +3811,24 @@
        as_fn_error $? "*** Please install Qt5 svg support - apt-get install libqt5svg5 ***" "$LINENO" 5
    fi

-# Arch Linux 64bit
+# Arch Linux 64bit & Alpine Linux
 elif test -f /usr/lib/libQt5Core.so
 then
+   if test -d /usr/lib/qt5
+   then
+       qtdir='qt5'
+   else
+       qtdir='qt'
+   fi
         echo "Found qt5 library in /usr/lib directory"
         # check libqt5svg5 library
-        if test -f /usr/lib/qt/plugins/imageformats/libqsvg.so
+        if test -f /usr/lib/$qtdir/plugins/imageformats/libqsvg.so
         then
                 echo "Found qt5 svg library"
         else
                 as_fn_error $? "*** Please install Qt5 svg support - pacman -S qt5-svg ***" "$LINENO" 5
         fi
-        if test -f /usr/lib/qt/plugins/iconengines/libqsvgicon.so
+        if test -f /usr/lib/$qtdir/plugins/iconengines/libqsvgicon.so
         then
                 echo "Found qt5 svg icon library"
         else

--- firetools-0.9.30/configure
+++ firetools-0.9.30/configure.new
@@ -3939,6 +3939,11 @@
        QMAKE=/usr/lib64/qt4/bin/qmake
    fi

+        # fix for Alpine Linux
+        if test -f /usr/lib/qt5/bin/qmake; then
+                QMAKE=/usr/lib/qt5/bin/qmake
+        fi
+
    if test -z "$QMAKE"
    then
        as_fn_error $? "qmake is missing, please install Qt4 or Qt5 development packages." "$LINENO" 5
```

I can create a pull request if the above fix is ok.

I'm temporarily building `firetools` with `qt4` until `qt5.60` is in the Alpine `main` repo (at the moment main is `5.50` & the `edge` repo is `5.60`).

**Comment by reinerh** [comment]
Have you tried building the current trunk?
There the Qt5 detection was reworked a bit.

**Comment by netblue30** [comment]
Yes, grab the version from git. I think it will solve the problems you are dealing with. It supports both Qt4 and Qt5 - actually it gets the Qt version from the version of qmake. I also gave up on detecting libqt5svg5, this is done at run time and a message window is opened if it is not installed. I am pushing to have the new version released next week, so the code will not change much until then.

**Comment by itoffshore** [comment]
The last patch above for `qt5` detection (similar to the fedora `qt4` fix) is still required for Alpine Linux using the current `master` (as `qmake` lives @ `/usr/lib/qt5/bin/qmake`). `qt4` builds without any patch.

After the next `release` & when Alpine has `qt5.60` in the `main` repo I will create a `pull request`.

**Comment by reinerh** [comment]
@itoffshore If Qt4 works, this means you have a qmake binary already in your PATH?
If so, you can tell it to switch to Qt5 by exporting `QT_SELECT=qt5`.
I don't know about Alpine packaging, but I guess there it is also possible to export it before starting the build?

**Comment by itoffshore** [comment]
yes `qt4` works because `qmake` is in the `$PATH`

exporting `QT_SELECT=qt5` in the build script did not work - so I think the 2nd patch will be need to be added eventually.

Nothing needs to be done until after the next `release`. Alpine has `qt5.50` in the main repo so I package with `qt4` temporarily until `qt5.60` is in main.

**Comment by reinerh** [comment]
Why do you need Qt 5.6? Firetools runs fine with Qt 5.5 in Debian.

What does `QT_SELECT=qt5 qmake --version` say on your system?
Something like this?

> Using Qt version **5.5.1** in /usr/lib/x86_64-linux-gnu

**Comment by itoffshore** [comment]
It builds with `qt5.60` but running on `qt5.51` (the `qt5` version in the `main` repo) fails with:

`Error relocating /usr/bin/firetools: qt_version_tag: symbol not found`

(running `firetools` on `qt5.60` works ok)

so the simplest solution is to build with `qt4` temporarily until the `main` repo is at `qt5.60`

**Comment by netblue30** [comment]
I added support to specify the location of qmake executable:

```
$ ./configure --prefix=/usr --with-qmake=/usr/lib/qt5/bin/qmake
```

Without --with-qmake, it will do "which qmake", as usual. I think this will fix it for everybody.
