### ISSUE TITLE
Cut a new release for 0.9.71

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#70]
@netblue30 I just noticed [this bug report](https://bugs.archlinux.org/task/77162) on the Arch Linux tracker. The GitHub page states 0.9.64 as latest release, which breaks firetools for users who have upgraded to firejail 0.9.72 (already in Arch Linux repo's). Can you cut a new release here please so the AL package maintainers can upgrade firetools accordingly?

https://github.com/netblue30/firetools/blob/bd75d3d95d85586a48c94cd65b8d8bbc94b1852f/configure.ac#L2

**Comment by netblue30** [comment]
I've just put out a new release!
